In [2]:
import pandas as pd
import numpy as np

In [3]:
n = pd.Series(np.random.randn(7))
print(n)
print()
print("on comparison--0 represents number is not available and 1 represents number available ")
for i in n:
    num = print(int(i))

    if num in range(-5,5):
        print(num)
        
print("the dimension is",n.ndim)
print("the size is ",n.size)
print("the axes is",n.axes)

0   -1.733234
1   -0.621124
2    1.879329
3    1.842052
4    1.845649
5   -1.476769
6    0.845388
dtype: float64

on comparison--0 represents number is not available and 1 represents number available 
-1
0
1
1
1
-1
0
the dimension is 1
the size is  7
the axes is [RangeIndex(start=0, stop=7, step=1)]


In [4]:
n = [[1,2,3],[4,5,6],[8,7,6]]
num = pd.DataFrame(n)
print(num.values)
print("the shape is ",num.ndim) 

[[1 2 3]
 [4 5 6]
 [8 7 6]]
the shape is  2


In [5]:
n = [[1,2,3,9],[4,5,6,5]]
num = pd.DataFrame(n,columns = ['id','p&s','ds','m1'],index = ['mark1','mark2'],dtype = int)
print(num.values)
print("the shape is ",num.ndim)
print(num)

[[1 2 3 9]
 [4 5 6 5]]
the shape is  2
       id  p&s  ds  m1
mark1   1    2   3   9
mark2   4    5   6   5


In [6]:
num = pd.read_csv('titanic.csv')
df = pd.DataFrame(num)
df.axes
df.values
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [7]:
ap = df.drop(['Parch','Pclass','Name'],axis = 1)
ap.head()

PassengerId  Survived     Sex   Age  SibSp            Ticket     Fare  \
0            1         0    male  22.0      1         A/5 21171   7.2500   
1            2         1  female  38.0      1          PC 17599  71.2833   
2            3         1  female  26.0      0  STON/O2. 3101282   7.9250   
3            4         1  female  35.0      1            113803  53.1000   
4            5         0    male  35.0      0            373450   8.0500   

  Cabin Embarked  
0   NaN        S  
1   C85        C  
2   NaN        S  
3  C123        S  
4   NaN        S

In [8]:
vp = ap.drop('SibSp',axis = 1)
vp.head()

PassengerId  Survived     Sex   Age            Ticket     Fare Cabin  \
0            1         0    male  22.0         A/5 21171   7.2500   NaN   
1            2         1  female  38.0          PC 17599  71.2833   C85   
2            3         1  female  26.0  STON/O2. 3101282   7.9250   NaN   
3            4         1  female  35.0            113803  53.1000  C123   
4            5         0    male  35.0            373450   8.0500   NaN   

  Embarked  
0        S  
1        C  
2        S  
3        S  
4        S

In [9]:
#In the below statements vp.Cabin!= 'Nan' is not working

In [22]:
#lp = vp[vp.Cabin != "Nan"]
lp = vp[vp.Cabin != 'Nan']
lp.head()

PassengerId  Survived     Sex   Age            Ticket     Fare Cabin  \
0            1         0    male  22.0         A/5 21171   7.2500   NaN   
1            2         1  female  38.0          PC 17599  71.2833   C85   
2            3         1  female  26.0  STON/O2. 3101282   7.9250   NaN   
3            4         1  female  35.0            113803  53.1000  C123   
4            5         0    male  35.0            373450   8.0500   NaN   

  Embarked  
0        S  
1        C  
2        S  
3        S  
4        S

In [26]:
lm = lp[lp.Cabin != 'Nan']
lm.head()

PassengerId  Survived     Sex   Age            Ticket     Fare Cabin  \
0            1         0    male  22.0         A/5 21171   7.2500   NaN   
1            2         1  female  38.0          PC 17599  71.2833   C85   
2            3         1  female  26.0  STON/O2. 3101282   7.9250   NaN   
3            4         1  female  35.0            113803  53.1000  C123   
4            5         0    male  35.0            373450   8.0500   NaN   

  Embarked  
0        S  
1        C  
2        S  
3        S  
4        S