In [15]:
import numpy as np
array_of_ones = np.ones((3,4))
print(array_of_ones)
array_of_ones
type(array_of_ones)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


numpy.ndarray

In [27]:
#specifying data type of numpy to list
#Use d-type function

arr_of_ones_int = np.ones((3,4),dtype = np.int16)
print(arr_of_ones_int)
print()
print(array_of_ones)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [28]:
arr_of_ones_int = np.ones((3,4),dtype = np.int16)
arr_of_ones_int

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int16)

In [32]:
array_empty = np.empty((2,3))

array_empty

array([[2.12199579e-314, 2.12199579e-314, 2.12199579e-314],
       [2.12199579e-314, 2.12199579e-314, 2.12199579e-314]])

In [36]:
#creating identity matrices

#np.eye()

arr_eye = np.eye((5),dtype = int)
arr_eye

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [47]:
# range is in python
# arrange is in numpy

#syntax -- arrange(start,stop,step)
import numpy as np

array_even = np.arange(2.4,20.6,3.5)
array_even

array([ 2.4,  5.9,  9.4, 12.9, 16.4, 19.9])

In [54]:
# 2-dimensionsal array

array_2d = np.array(((2,4,6),(3,5,8)))
array_2d

array([[2, 4, 6],
       [3, 5, 8]])

In [51]:
#how to verify 2d- array

array_2d.shape

(2, 3)

In [61]:
# how to create n-dimensional array... by using '.reshape()'

array_nd = np.arange(6).reshape(3,2)
array_nd

array([[0, 1],
       [2, 3],
       [4, 5]])