In [8]:
import numpy as np
a = np.arange(10)**3
a

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

In [11]:
print(a[2])
print(a[1:5])

8
[ 1  8 27 64]


In [18]:
print(a[2:-4])

[  8  27  64 125]


In [63]:
arr = np.ones((3,3),dtype = np.int16)
print(arr)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [36]:
arr_eye = np.eye((4), dtype =int)
arr_eye

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [51]:

arr = np.empty((3,4))
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [54]:
arr = np.array(((2,3,4),(5,6,7),(1,2,3)))
arr

array([[2, 3, 4],
       [5, 6, 7],
       [1, 2, 3]])

In [55]:
arr.shape

(3, 3)

In [62]:
arr = np.arange(12).reshape(4,3)
arr

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])