In [16]:
import numpy as np

in_round = np.array([11.1, 21.55,51.67,18.382,6.5])
print("original ")
in_round

print("after rounding")

print(np.around(in_round))
print()
print("Rounding decimals to 1")
print(np.around(in_round,  decimals = 1))
print()
print("Rounding number to its nearest multiples of 10")
print(np.around(in_round,  decimals = -1))

original 
after rounding
[11. 22. 52. 18.  6.]

Rounding decimals to 1
[11.1 21.6 51.7 18.4  6.5]

Rounding number to its nearest multiples of 10
[10. 20. 50. 20. 10.]


In [22]:
# Short program on floor and ceil

import numpy as np

in_val = np.array([1.5,-1.5,2.45,-2.45,3.89,-3.89])

print('original values')
print(in_val)
print()
print('floored values')
print(np.floor(in_val))
print()
print('ceil values')
print(np.ceil(in_val))

original values
[ 1.5  -1.5   2.45 -2.45  3.89 -3.89]

floored values
[ 1. -2.  2. -3.  3. -4.]

ceil values
[ 2. -1.  3. -2.  4. -3.]


In [28]:
# calculator using numpy

import numpy as np

in_val = np.arange(9,dtype = np.float).reshape(3,3)

print('first array')
print(in_val)
print()
print('second array')
sub = np.array([10,10,10])
print(sub)
print()
print("adding 2 arrays")
print(np.add(in_val,sub))
print()
print("subtracting 2 arrays")
print(np.subtract(in_val,sub))
print()
print("multiplying 2 arrays")
print(np.multiply(in_val,sub))
print()
print("dividing 2 arrays")
print(np.divide(in_val,sub))

first array
[[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]

second array
[10 10 10]

adding 2 arrays
[[10. 11. 12.]
 [13. 14. 15.]
 [16. 17. 18.]]

subtracting 2 arrays
[[-10.  -9.  -8.]
 [ -7.  -6.  -5.]
 [ -4.  -3.  -2.]]

multiplying 2 arrays
[[ 0. 10. 20.]
 [30. 40. 50.]
 [60. 70. 80.]]

dividing 2 arrays
[[0.  0.1 0.2]
 [0.3 0.4 0.5]
 [0.6 0.7 0.8]]
