In [1]:
import numpy as np

In [7]:
num = np.arange(12)**2
print(num)
num

[  0   1   4   9  16  25  36  49  64  81 100 121]


array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121],
      dtype=int32)

In [8]:
print(num[3])

9


In [9]:
print(num[2:-2])

[ 4  9 16 25 36 49 64 81]


In [14]:
for i in num:
    print(int(i**(3/4)))

0
1
2
5
8
11
14
18
22
27
31
36


In [23]:
info = np.array([['alice','bob','charlie','mike','naeid'],
                [11,22,33,44,55],
                [1200,1400,2100,1900,900]])
for i in info:
    print(i)
    print()

['alice' 'bob' 'charlie' 'mike' 'naeid']

['11' '22' '33' '44' '55']

['1200' '1400' '2100' '1900' '900']



In [24]:
for i in info.flatten():
    print(i)

alice
bob
charlie
mike
naeid
11
22
33
44
55
1200
1400
2100
1900
900


In [25]:
for i in info.flatten(order ='F'):
    print(i)

alice
11
1200
bob
22
1400
charlie
33
2100
mike
44
1900
naeid
55
900


In [28]:
# using iterator

arr = np.arange(12).reshape(3,4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [35]:
for i in np.nditer(arr):
    print(i, end=' ')

0 1 2 3 4 5 6 7 8 9 10 11 

In [34]:
for i in np.nditer(arr,order = 'F'):
    print(i,end=' ')

0 4 8 1 5 9 2 6 10 3 7 11 

In [40]:
arr.shape

(3, 4)

In [41]:
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [42]:
arr.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [55]:
np.split(arr,3)

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]

In [57]:
#Splitting of arrays using hsplit, vsplit

In [63]:
arr = np.arange(12)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [67]:
#possibilities
'''np.split(arr,2),np.split(arr,3),np.split(arr,4),np.split(arr,6)'''
np.split(arr,6)

[array([0, 1]),
 array([2, 3]),
 array([4, 5]),
 array([6, 7]),
 array([8, 9]),
 array([10, 11])]

In [68]:
split_ex = np.array([['germany','rome','hungery','austria'],
                    ['berlin','paris','virginia','budapest']])

In [72]:
city_main, city_op = np.hsplit(split_ex,2)
print(city_main)

[['germany' 'rome']
 ['berlin' 'paris']]


In [73]:
print(city_op)

[['hungery' 'austria']
 ['virginia' 'budapest']]


In [74]:
city_main, city_op = np.vsplit(split_ex,2)
print(city_main)

[['germany' 'rome' 'hungery' 'austria']]


In [75]:
print(city_op)

[['berlin' 'paris' 'virginia' 'budapest']]


In [77]:
countries, capitals = split_ex
print(countries)
print()
print(capitals)

['germany' 'rome' 'hungery' 'austria']

['berlin' 'paris' 'virginia' 'budapest']
